import type { Subject, Topic, Question } from "../types";

// Mock data for demo purposes
export const mockSubjects: Subject[] = [
  {
    id: 1,
    name: "Mathematics",
    slug: "mathematics",
    icon: "Calculator",
  },
  {
    id: 2,
    name: "Physics",
    slug: "physics",
    icon: "Atom",
  },
  {
    id: 3,
    name: "Chemistry",
    slug: "chemistry",
    icon: "Flask",
  },
  {
    id: 4,
    name: "Biology",
    slug: "biology",
    icon: "Microscope",
  },
  {
    id: 5,
    name: "Use of English",
    slug: "use-of-english",
    icon: "BookOpen",
  },
  {
    id: 6,
    name: "Economics",
    slug: "economics",
    icon: "TrendingUp",
  },
  {
    id: 7,
    name: "Government",
    slug: "government",
    icon: "Landmark",
  },
  {
    id: 8,
    name: "Literature in English",
    slug: "literature-in-english",
    icon: "ScrollText",
  },
];

export const mockTopics: Topic[] = [
  {
    id: 1,
    subjectId: 1,
    name: "Calculus",
    slug: "calculus",
    isHighYield: true,
    content: "# Calculus\n\nCalculus is a branch of mathematics that deals with rates of change and accumulation.",
    summary: "Core mathematical concepts for advanced problem solving",
    commonTraps: ["Forgetting the chain rule", "Sign errors in derivatives"],
  },
  {
    id: 2,
    subjectId: 1,
    name: "Linear Algebra",
    slug: "linear-algebra",
    isHighYield: true,
    content: "# Linear Algebra\n\nLinear algebra is the study of vectors, matrices, and linear transformations.",
    summary: "Essential for understanding systems of equations and transformations",
  },
  {
    id: 5,
    subjectId: 1,
    name: "Probability and Statistics",
    slug: "probability-and-statistics",
    isHighYield: true,
    content: "# Probability and Statistics\n\nLearn events, probability laws, and interpretation of data sets.",
    summary: "Frequently tested data interpretation and probability questions",
  },
  {
    id: 6,
    subjectId: 1,
    name: "Trigonometry",
    slug: "trigonometry",
    isHighYield: false,
    content: "# Trigonometry\n\nCore trig identities, ratios, and angle relationships.",
    summary: "Angle and identity manipulation for mixed questions",
  },
  {
    id: 3,
    subjectId: 2,
    name: "Mechanics",
    slug: "mechanics",
    isHighYield: true,
    content: "# Mechanics\n\nMechanics is the branch of physics that deals with motion and forces.",
    summary: "Fundamental physics principles governing motion",
  },
  {
    id: 7,
    subjectId: 2,
    name: "Waves and Sound",
    slug: "waves-and-sound",
    isHighYield: true,
    content: "# Waves and Sound\n\nStudy wave properties, sound propagation, and resonance.",
    summary: "Common objective questions around wave equations and sound behavior",
  },
  {
    id: 8,
    subjectId: 2,
    name: "Electricity and Magnetism",
    slug: "electricity-and-magnetism",
    isHighYield: true,
    content: "# Electricity and Magnetism\n\nCurrent, voltage, electric fields, and magnetic effects.",
    summary: "Core formulas and circuit interpretation",
  },
  {
    id: 9,
    subjectId: 2,
    name: "Thermal Physics",
    slug: "thermal-physics",
    isHighYield: false,
    content: "# Thermal Physics\n\nHeat transfer, temperature scales, and gas laws.",
    summary: "Conceptual and formula-based heat questions",
  },
  {
    id: 4,
    subjectId: 3,
    name: "Organic Chemistry",
    slug: "organic-chemistry",
    isHighYield: true,
    content: "# Organic Chemistry\n\nOrganic chemistry studies carbon-containing compounds.",
    summary: "Chemistry of carbon compounds and their reactions",
  },
  {
    id: 10,
    subjectId: 3,
    name: "Chemical Equilibrium",
    slug: "chemical-equilibrium",
    isHighYield: true,
    content: "# Chemical Equilibrium\n\nEquilibrium constants, Le Chatelier principle, and reaction shifts.",
    summary: "Very frequent in JAMB chemistry sections",
  },
  {
    id: 11,
    subjectId: 3,
    name: "Stoichiometry",
    slug: "stoichiometry",
    isHighYield: true,
    content: "# Stoichiometry\n\nMole concept, balancing equations, and yield calculations.",
    summary: "Calculation-heavy area with high scoring potential",
  },
  {
    id: 12,
    subjectId: 3,
    name: "Separation Techniques",
    slug: "separation-techniques",
    isHighYield: false,
    content: "# Separation Techniques\n\nFiltration, distillation, chromatography, and extraction.",
    summary: "Foundational practical chemistry principles",
  },
  {
    id: 13,
    subjectId: 4,
    name: "Ecology",
    slug: "ecology",
    isHighYield: true,
    content: "# Ecology\n\nStudy ecosystems, food chains, and population dynamics.",
    summary: "Frequent direct theory questions",
  },
  {
    id: 14,
    subjectId: 4,
    name: "Genetics",
    slug: "genetics",
    isHighYield: true,
    content: "# Genetics\n\nInheritance patterns, chromosomes, and variation.",
    summary: "Punnett-square and inheritance reasoning",
  },
  {
    id: 15,
    subjectId: 4,
    name: "Human Physiology",
    slug: "human-physiology",
    isHighYield: false,
    content: "# Human Physiology\n\nBody systems and biological regulation.",
    summary: "System function and adaptation principles",
  },
  {
    id: 16,
    subjectId: 5,
    name: "Lexis and Structure",
    slug: "lexis-and-structure",
    isHighYield: true,
    content: "# Lexis and Structure\n\nGrammar, usage, and sentence completion strategies.",
    summary: "High-frequency grammar and usage corrections",
  },
  {
    id: 17,
    subjectId: 5,
    name: "Comprehension",
    slug: "english-comprehension",
    isHighYield: true,
    content: "# Comprehension\n\nReading passages and extracting meaning accurately.",
    summary: "Inference and direct meaning questions",
  },
  {
    id: 18,
    subjectId: 5,
    name: "Oral English",
    slug: "oral-english",
    isHighYield: false,
    content: "# Oral English\n\nStress, intonation, and pronunciation patterns.",
    summary: "Pronunciation and stress placement questions",
  },
  {
    id: 19,
    subjectId: 6,
    name: "Demand and Supply",
    slug: "demand-and-supply",
    isHighYield: true,
    content: "# Demand and Supply\n\nMarket equilibrium, shifts, and elasticity basics.",
    summary: "Foundational and repeatedly tested market theory",
  },
  {
    id: 20,
    subjectId: 6,
    name: "National Income",
    slug: "national-income",
    isHighYield: true,
    content: "# National Income\n\nGDP concepts, measurement methods, and limitations.",
    summary: "Computation and concept-based objective items",
  },
  {
    id: 21,
    subjectId: 6,
    name: "Money and Banking",
    slug: "money-and-banking",
    isHighYield: false,
    content: "# Money and Banking\n\nCentral bank tools and monetary policy.",
    summary: "Policy and institution-based questions",
  },
  {
    id: 22,
    subjectId: 7,
    name: "Constitutional Development",
    slug: "constitutional-development",
    isHighYield: true,
    content: "# Constitutional Development\n\nEvolution of constitutional frameworks in Nigeria.",
    summary: "Timeline and feature-based question pattern",
  },
  {
    id: 23,
    subjectId: 7,
    name: "Arms of Government",
    slug: "arms-of-government",
    isHighYield: true,
    content: "# Arms of Government\n\nExecutive, legislature, judiciary and checks/balances.",
    summary: "Direct role and function comparison questions",
  },
  {
    id: 24,
    subjectId: 7,
    name: "Citizenship and Rule of Law",
    slug: "citizenship-and-rule-of-law",
    isHighYield: false,
    content: "# Citizenship and Rule of Law\n\nRights, duties, and legal order fundamentals.",
    summary: "Conceptual civic and governance questions",
  },
  {
    id: 25,
    subjectId: 8,
    name: "Poetry",
    slug: "poetry",
    isHighYield: true,
    content: "# Poetry\n\nThemes, devices, and interpretation skills for selected poems.",
    summary: "Imagery, tone, and theme recognition",
  },
  {
    id: 26,
    subjectId: 8,
    name: "Drama",
    slug: "drama",
    isHighYield: true,
    content: "# Drama\n\nPlot, characterization, and dramatic techniques.",
    summary: "Text interpretation and character analysis",
  },
  {
    id: 27,
    subjectId: 8,
    name: "Prose",
    slug: "prose",
    isHighYield: false,
    content: "# Prose\n\nNarrative techniques and thematic interpretation.",
    summary: "Comprehension of prose passages and set texts",
  },
];

export const mockQuestions: Question[] = [
  {
    id: 1,
    topicId: 1,
    content: "What is the derivative of x²?",
    options: {
      A: "x",
      B: "2x",
      C: "x²",
      D: "2x²",
    },
    correctOption: "B",
    explanation: "The derivative of x² is 2x using the power rule.",
  },
  {
    id: 2,
    topicId: 1,
    content: "What is the integral of 2x?",
    options: {
      A: "x²",
      B: "x² + C",
      C: "2",
      D: "2x²",
    },
    correctOption: "B",
    explanation: "The integral of 2x is x² + C, where C is the constant of integration.",
  },
];