export const NIGERIAN_INSTITUTIONS: string[] = [
  "University of Ibadan (UI)",
  "University of Lagos (UNILAG)",
  "Obafemi Awolowo University (OAU)",
  "University of Nigeria, Nsukka (UNN)",
  "Ahmadu Bello University (ABU)",
  "University of Ilorin (UNILORIN)",
  "University of Benin (UNIBEN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Calabar (UNICAL)",
  "University of Jos (UNIJOS)",
  "Bayero University Kano (BUK)",
  "Usmanu Danfodiyo University, Sokoto (UDUS)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "University of Maiduguri (UNIMAID)",
  "Federal University of Technology Akure (FUTA)",
  "Federal University of Technology Owerri (FUTO)",
  "Federal University of Technology Minna (FUTMINNA)",
  "Modibbo Adama University, Yola (MAU)",
  "Abubakar Tafawa Balewa University (ATBU)",
  "Michael Okpara University of Agriculture, Umudike (MOUAU)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University, Lafia (FULAFIA)",
  "Federal University, Lokoja (FULOKOJA)",
  "Federal University, Otuoke (FUOTUOKE)",
  "Federal University, Kashere (FUKASHERE)",
  "Federal University, Dutse (FUD)",
  "Federal University, Dutsin-Ma (FUDMA)",
  "Federal University, Gashua (FUGASHUA)",
  "Federal University, Gusau (FUGUS)",
  "Federal University, Birnin Kebbi (FUBK)",
  "Federal University, Wukari (FUWUKARI)",
  "Federal University, Ndifu-Alike (FUNAI)",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Kashere (FUK)",
  "Alex Ekwueme Federal University Ndufu-Alike (AE-FUNAI)",
  "Nigerian Defence Academy (NDA)",
  "Nigerian Army University Biu (NAUB)",
  "Air Force Institute of Technology (AFIT)",
  "Maritime University, Okerenkoko",
  "University of Abuja (UNIABUJA)",
  "Lagos State University (LASU)",
  "Olabisi Onabanjo University (OOU)",
  "Ekiti State University (EKSU)",
  "Adekunle Ajasin University, Akungba (AAUA)",
  "Ondo State University of Science and Technology (OAUSTECH)",
  "Osun State University (UNIOSUN)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Rivers State University (RSU)",
  "Delta State University (DELSU)",
  "Ambrose Alli University (AAU)",
  "Ebonyi State University (EBSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Benue State University (BSU)",
  "Kogi State University, Anyigba (KSU)",
  "Nasarawa State University, Keffi (NSUK)",
  "Kaduna State University (KASU)",
  "Kano University of Science and Technology, Wudil (KUST)",
  "Yusuf Maitama Sule University Kano (YUMSUK)",
  "Kebbi State University of Science and Technology, Aliero (KSUSTA)",
  "Taraba State University (TSU)",
  "Sokoto State University (SSU)",
  "Zamfara State University",
  "Adamawa State University (ADSU)",
  "Gombe State University (GSU)",
  "Borno State University",
  "Bauchi State University, Gadau (BASUG)",
  "Plateau State University (PLASU)",
  "Ignatius Ajuru University of Education (IAUE)",
  "Tai Solarin University of Education (TASUED)",
  "Emmanuel Alayande University of Education",
  "Abia State University (ABSU)",
  "Imo State University (IMSU)",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Cross River University of Technology (CRUTECH)",
  "Akwa Ibom State University (AKSU)",
  "Niger Delta University (NDU)",
  "Confluence University of Science and Technology",
  "University of Medical Sciences Ondo (UNIMED)",
  "Lagos State University of Education (LASUED)",
  "Lagos State University of Science and Technology (LASUSTECH)",
  "Bamidele Olumilua University of Education, Science and Technology",
  "University of Africa, Toru-Orua",
  "Benson Idahosa University",
  "Covenant University",
  "Afe Babalola University (ABUAD)",
  "Babcock University",
  "Bowen University",
  "Redeemer's University",
  "Pan-Atlantic University",
  "Nile University of Nigeria",
  "American University of Nigeria (AUN)",
  "Igbinedion University",
  "Caleb University",
  "Ajayi Crowther University",
  "Al-Hikmah University",
  "Crawford University",
  "Elizade University",
  "Fountain University",
  "Joseph Ayo Babalola University",
  "Lead City University",
  "Madonna University",
  "Mountain Top University",
  "Paul University",
  "Renaissance University",
  "Salem University",
  "Southwestern University",
  "Summit University",
  "Veritas University",
  "Wellspring University",
  "Landmark University",
  "Oduduwa University",
  "Achievers University",
  "Adeleke University",
  "KolaDaisi University",
  "McPherson University",
  "Kings University",
  "Augustine University",
  "Christopher University",
  "Edo State University Uzairue",
  "Miva Open University",
  "National Open University of Nigeria (NOUN)",
  "Yaba College of Technology (YABATECH)",
  "Federal Polytechnic Ilaro",
  "Federal Polytechnic Ede",
  "Federal Polytechnic Offa",
  "Federal Polytechnic Nekede",
  "Federal Polytechnic Oko",
  "Federal Polytechnic Ado-Ekiti",
  "Federal Polytechnic Bida",
  "Federal Polytechnic Kaura Namoda",
  "Federal Polytechnic Damaturu",
  "Federal Polytechnic Nasarawa",
  "Kaduna Polytechnic",
  "Auchi Polytechnic",
  "Kwara State Polytechnic",
  "Lagos State Polytechnic (LASPOTECH)",
  "Ramat Polytechnic",
  "Abia State Polytechnic",
  "The Polytechnic Ibadan",
  "Moshood Abiola Polytechnic (MAPOLY)",
  "Rufus Giwa Polytechnic",
  "Ogun State Institute of Technology",
  "Delta State Polytechnic, Otefe",
  "Delta State Polytechnic, Ozoro",
  "Delta State Polytechnic, Ogwashi-Uku",
  "Imo State Polytechnic",
  "Akwa Ibom State Polytechnic",
  "Benue State Polytechnic",
  "Nuhu Bamalli Polytechnic",
  "Nasarawa State Polytechnic",
  "Abraham Adesanya Polytechnic",
  "Gateway ICT Polytechnic",
  "Osun State Polytechnic, Iree",
  "Abubakar Tatari Ali Polytechnic",
  "College of Education, Zuba",
  "Federal College of Education (Technical), Akoka",
  "Federal College of Education, Abeokuta",
  "Federal College of Education, Kano",
  "Federal College of Education, Okene",
  "Federal College of Education, Pankshin",
  "Federal College of Education, Yola",
  "Aminu Saleh College of Education",
  "College of Education, Ikere-Ekiti",
  "Adeniran Ogunsanya College of Education",
  "Kashim Ibrahim College of Education",
  "Nwafor Orizu College of Education",
  "Alvan Ikoku Federal University of Education",
  "Tai Solarin College of Education",
  "Emmanuel Alayande College of Education"
];

export const COMMON_NIGERIAN_COURSES: string[] = [
  "Medicine and Surgery",
  "Dentistry",
  "Pharmacy",
  "Nursing",
  "Medical Laboratory Science",
  "Physiotherapy",
  "Radiography",
  "Public Health",
  "Anatomy",
  "Physiology",
  "Biochemistry",
  "Microbiology",
  "Computer Science",
  "Cyber Security",
  "Software Engineering",
  "Information Technology",
  "Data Science",
  "Computer Engineering",
  "Electrical and Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Petroleum Engineering",
  "Agricultural Engineering",
  "Mechatronics Engineering",
  "Architecture",
  "Building",
  "Quantity Surveying",
  "Surveying and Geoinformatics",
  "Urban and Regional Planning",
  "Estate Management",
  "Law",
  "International Relations",
  "Political Science",
  "Public Administration",
  "Economics",
  "Accounting",
  "Business Administration",
  "Banking and Finance",
  "Marketing",
  "Insurance",
  "Taxation",
  "Mass Communication",
  "Journalism and Media Studies",
  "Linguistics",
  "English Language",
  "Literature in English",
  "History and International Studies",
  "Philosophy",
  "Psychology",
  "Sociology",
  "Criminology and Security Studies",
  "Geography",
  "Environmental Management",
  "Geology",
  "Geophysics",
  "Statistics",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Botany",
  "Zoology",
  "Agriculture",
  "Agricultural Economics",
  "Animal Science",
  "Crop Science",
  "Fisheries and Aquaculture",
  "Forestry and Wildlife",
  "Food Science and Technology",
  "Nutrition and Dietetics",
  "Home Economics",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Physics",
  "Education and Mathematics",
  "Education and Economics",
  "Education and English",
  "Guidance and Counselling",
  "Early Childhood Education",
  "Primary Education Studies",
  "Islamic Studies",
  "Christian Religious Studies",
  "Arabic",
  "French",
  "Fine and Applied Arts",
  "Theatre Arts",
  "Music",
  "Nautical Science",
  "Marine Engineering",
  "Transport Management",
  "Library and Information Science",
  "Office Technology and Management",
  "Entrepreneurship"
];

export const ALL_JAMB_SUBJECTS: string[] = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Economics",
  "Government",
  "Literature in English",
  "Commerce",
  "Accounting",
  "Geography",
  "Agricultural Science",
  "History",
  "Christian Religious Studies",
  "Islamic Religious Studies",
  "Civic Education",
  "French",
  "Arabic",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Fine Art",
  "Music",
  "Home Economics",
  "Technical Drawing"
];

type Rule = {
  keywords: string[];
  subjects: [string, string, string];
};

const COURSE_TO_SUBJECT_RULES: Rule[] = [
  {
    keywords: ["medicine", "dentistry", "nursing", "pharmacy", "physio", "radiography", "medical"],
    subjects: ["Biology", "Chemistry", "Physics"]
  },
  {
    keywords: ["biochemistry", "microbiology", "zoology", "botany", "physiology", "anatomy", "public health"],
    subjects: ["Biology", "Chemistry", "Physics"]
  },
  {
    keywords: ["engineering", "computer", "cyber", "software", "data science", "mechatronics", "architecture", "building"],
    subjects: ["Mathematics", "Physics", "Chemistry"]
  },
  {
    keywords: ["geology", "geophysics", "surveying", "geoinformatics", "urban", "estate"],
    subjects: ["Mathematics", "Physics", "Geography"]
  },
  {
    keywords: ["law"],
    subjects: ["Literature in English", "Government", "Christian Religious Studies"]
  },
  {
    keywords: ["mass communication", "journalism", "linguistics", "english", "theatre", "music", "fine"],
    subjects: ["Literature in English", "Government", "Christian Religious Studies"]
  },
  {
    keywords: ["international relations", "political", "public administration", "history", "philosophy", "sociology", "psychology", "criminology"],
    subjects: ["Government", "Economics", "Literature in English"]
  },
  {
    keywords: ["accounting", "banking", "finance", "economics", "business", "marketing", "insurance", "tax"],
    subjects: ["Mathematics", "Economics", "Commerce"]
  },
  {
    keywords: ["statistics", "mathematics", "physics", "chemistry"],
    subjects: ["Mathematics", "Physics", "Chemistry"]
  },
  {
    keywords: ["agric", "animal", "crop", "fisheries", "forestry", "food", "nutrition"],
    subjects: ["Biology", "Chemistry", "Agricultural Science"]
  },
  {
    keywords: ["education"],
    subjects: ["Mathematics", "Economics", "Government"]
  },
  {
    keywords: ["religious", "islamic", "christian", "arabic", "french"],
    subjects: ["Literature in English", "Government", "Christian Religious Studies"]
  },
  {
    keywords: ["nautical", "marine", "transport"],
    subjects: ["Mathematics", "Physics", "Geography"]
  }
];

export function inferJambSubjectsForCourse(course: string): [string, string, string] {
  const normalized = course.toLowerCase().trim();
  const hit = COURSE_TO_SUBJECT_RULES.find((rule) =>
    rule.keywords.some((keyword) => normalized.includes(keyword))
  );

  // Safe default for most STEM and broad UTME pathways.
  return hit?.subjects ?? ["Mathematics", "Physics", "Chemistry"];
}
